config/routes.rb
Rails.application.routes.draw do

  root 'paginas#inicio'

  devise_for :usuarios,
             path: '',
             path_names: {sign_in: 'ingresar', sign_out: 'salir', edit: 'perfil', sign_up: 'registrar'},
             controllers: {registrations: 'registrations'}

  resources :consentimientos
  resources :pacientes
  resources :fotos
  resources :fotodiagnosticos
  resources :campodiagnosticos
  resources :seguimientos

end

app/models/paciente.rb
class Paciente < ApplicationRecord
  belongs_to :usuario
  has_many :fotos
  has_many :fotodiagnosticos
  has_many :seguimientos
end

app/controllers/pacientes_controller.rb
class PacientesController < ApplicationController
  before_action :set_paciente, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_usuario!, except: [:index, :show]

  # GET /pacientes
  # GET /pacientes.json
  def index
    @pacientes = Paciente.all.order("created_at desc")
  end

  # GET /pacientes/1
  # GET /pacientes/1.json
  def show
  end

  # GET /pacientes/new
  def new
    @paciente = Paciente.new
  end

  # GET /pacientes/1/edit
  def edit
  end

  # POST /pacientes
  # POST /pacientes.json
  def create
    @paciente = current_usuario.pacientes.new(paciente_params)

    respond_to do |format|
      if @paciente.save
        format.html { redirect_to @paciente, notice: 'Paciente fue creado con éxito.' }
        format.json { render :show, status: :created, location: @paciente }
      else
        format.html { render :new }
        format.json { render json: @paciente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pacientes/1
  # PATCH/PUT /pacientes/1.json
  def update
    respond_to do |format|
      if @paciente.update(paciente_params)
        format.html { redirect_to @paciente, notice: 'Paciente fue actualizado con éxito.' }
        format.json { render :show, status: :ok, location: @paciente }
      else
        format.html { render :edit }
        format.json { render json: @paciente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pacientes/1
  # DELETE /pacientes/1.json
  def destroy
    @paciente.destroy
    respond_to do |format|
      format.html { redirect_to pacientes_url, notice: 'Paciente fue destruido con éxito.' }
      format.json { head :no_content }
    end
  end

  private

    def set_paciente
      @paciente = Paciente.find(params[:id])
    end

    def paciente_params
      params.require(:paciente).permit(:nombre, :apellido, :genero, :tipo_documento, :documento, :f_nacimiento, :edad, :pais_nacimiento, :n_departamento, :n_ciudad, :aseguradora, :raza, :etnia, :pais_residencia, :r_departamento, :r_ciudad, :r_direccion, :estado, :pais_estancia, :e_departamento, :e_ciudad, :religion, :celular, :telefono, :correo, :usuario_id)
    end
end

app/helpers/pacientes_helper.rb
module PacientesHelper
end

app/views/pacientes/_form.html.erb
<%= form_for(paciente) do |f| %>
  <% if paciente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(paciente.errors.count, "error") %> prohibited this paciente from being saved:</h2>

      <ul>
      <% paciente.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="col-md-8 oro-form__content">
      <div class="container-fluid">
        <div  id="basicos" class="oro-form__group">
          <div class="row">
            <h4 class="oro-form__breack">Datos Básicos</h4>
          </div>
          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
                <%= f.label :nombre, class: 'form-label' %>
                <%= f.text_field :nombre , class: 'form-control'%>
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-group">
                <%= f.label :apellido, class: 'form-label' %>
                <%= f.text_field :apellido, class: 'form-control' %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
                <%= f.label :tipo_documento, class: 'form-label' %>
                <%= f.select :tipo_documento,[['Cédula Ciudadania', 'cedula ciudadania'], ['Tarjeta Identidad', 'tarjeta identidad'], ['Cédula Extranjería', 'cedula extranjería'], ['Registro Civil','registro civil'],['Pasaporte','pasaporte']], {},{ class: 'form-control'}  %>
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-group">
                <%= f.label :documento, class: 'form-label' %>
                <%= f.text_field :documento, class: 'form-control' %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
                <%= f.label :genero, class: 'form-label' %>
                <%= f.select :genero, [["Masculino", "masculino"], ["Femenino", "femenino"]],{}, 'class': "form-control" %>
              </div>
            </div>
            <div class="col-md-4">
              <div class="form-group">
                <%= f.label :'fecha nacimiento', class: 'form-label' %>
                <%= f.date_field :f_nacimiento, class: 'form-control' %>
              </div>
            </div>
            <div class="col-md-2">
              <div class="form-group">
                <%= f.label :edad, class: 'form-label'  %>
                <%= f.text_field :edad, class: 'form-control' %>
              </div>
            </div>
          </div>
        </div>
        <div id="demograficos" class="oro-form__group">
          <div class="row">
            <h4 class="oro-form__breack">Datos Demográficos</h4>
          </div>
          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
                <%= f.label :país_nacimiento, class: 'form-label' %>
                <%= f.text_field :pais_nacimiento , class: 'form-control' %>
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-group">
                <%= f.label :'Departamento', class: 'form-label' %>
                <%= f.text_field :n_departamento , class: 'form-control' %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
                <%= f.label :'Ciudad', class: 'form-label' %>
                <%= f.text_field :n_ciudad , class: 'form-control' %>
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-group">
                <%= f.label :aseguradora, class: 'form-label' %>
                <%= f.text_field :aseguradora , class: 'form-control' %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
                <%= f.label :raza, class: 'form-label' %>
                <%= f.text_field :raza , class: 'form-control' %>
              </div>
            </div>
            <!--
            <div class="col-md-6">
              <div class="form-group">
                <%# <%= f.label :etnia, class: 'form-label' %>
                <%# <%= f.text_field :etnia , class: 'form-control' %>
              </div>
            </div>-->
          </div>

        </div>
        <div id="contacto" class="oro-form__group">
          <div class="row">
            <h4 class="oro-form__breack">Datos Contacto</h4>
          </div>
          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
                <%= f.label :'país_residencia', class: 'form-label' %>
                <%= f.text_field :pais_residencia , class: 'form-control' %>
              </div>
            </div>
            <!--<div class="col-md-6">
              <div class="form-group">
                <%# <%= f.label :'Departamento Residencia', class: 'form-label' %>
                <%# <%= f.text_field :r_departamento , class: 'form-control' %>
              </div>
            </div>-->
          </div>
          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
                <%= f.label :'Ciudad Residencia', class: 'form-label' %>
                <%= f.text_field :r_ciudad , class: 'form-control' %>
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-group">
                <%= f.label :'Dirección Residencia', class: 'form-label' %>
                <%= f.text_field :r_direccion , class: 'form-control' %>
              </div>
            </div>
          </div>
          <div class="row">
            <!--
            <div class="col-md-6">
              <div class="form-group">
               <%# <%= f.label :estado, class: 'form-label' %>
               <%# <%= f.text_field :estado , class: 'form-control' %>
              </div>
            </div>-->
            <!--<div class="col-md-6">
              <div class="form-group">
                <%# <%= f.label :pais_estancia, class: 'form-label' %>
                <%# <%= f.text_field :pais_estancia , class: 'form-control' %>
              </div>
            </div> -->
          </div>
          <div class="row">
           <!-- <div class="col-md-6">
              <div class="form-group">
                <%# <%= f.label :'Departamento Estancia', class: 'form-label' %>
                <%# <%= f.text_field :e_departamento , class: 'form-control' %>
              </div>
            </div> -->
            <!-- <div class="col-md-6">
              <div class="form-group">
                <%# <%= f.label :'Ciudad de Estancia', class: 'form-label' %>
                <%# <%= f.text_field :e_ciudad , class: 'form-control' %>
              </div>
            </div> -->
          </div>
          <div class="row">
            <!--<div class="col-md-6">
              <div class="form-group">
                <%# <%= f.label :religion, class: 'form-label' %>
                <%# <%= f.text_field :religion , class: 'form-control' %>
              </div>
            </div>  -->
            <div class="col-md-6">
              <div class="form-group">
                <%= f.label :celular, class: 'form-label' %>
                <%= f.text_field :celular , class: 'form-control' %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
                <%= f.label :teléfono, class: 'form-label' %>
                <%= f.text_field :telefono , class: 'form-control' %>
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-group">
                <%= f.label :email, class: 'form-label' %>
                <%= f.text_field :correo , class: 'form-control' %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-group">
                <div class="actions">
                  <input type="submit" class="btn btn-primary btn-block" value="Finalizar">
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
  </div>
  <div class="col-md-4 oro-form__control">
    <ul class="nav navbar">
      <li class="navbar-link oro-form__check"><a href="#basicos" onclick=""><i class="glyphicon glyphicon-check"></i> Datos Básicos</a></li>
      <li class="navbar-link oro-form__check"><a href="#demograficos" onclick=""><i class="glyphicon glyphicon-check"></i> Datos Demográficos</a></li>
      <li class="navbar-link oro-form__check"><a href="#contacto" onclick=""><i class="glyphicon glyphicon-check"></i> Datos Contacto</a></li>
    </ul>
  </div>
  <script !src="">
    $(document).ready(function(){
        loadDatosBasicos();
    })
  </script>
<% end %>

app/views/pacientes/edit.html.erb
<div class="row oro-paciente__form">
  <h1>Editar Paciente</h1>
  <%= render 'form', paciente: @paciente %>
</div>
<div class="row oro-paciente__options">
  <%= link_to 'Ver', @paciente %> |
  <%= link_to 'Regresar', pacientes_path %>
</div>

app/views/pacientes/index.html.erb
<%= render 'shared/sidebar/pacientes' %>
<div class="oro-main-ui container-fluid">
  <div class="oro-main__actions">
    <div class="btn-group pull-right">
      <%if @pacientes.count == 0 %>
        <div class="oro-help oro-help--nuevo-paciente">
          <p class="oro-help__texto">
            Crear tu primer paciente
          </p>
        </div>
      <% end %>
      <form action="/pacientes/new" >
        <input type="submit" value="Nuevo Paciente" class="btn btn-default">
      </form>
    </div>
  </div>
  <br>
<%if @pacientes.count > 0 %>
    <div class="oro-paciente__list hidden">
      <% @pacientes.each do |paciente| %>
        <div class="oro-paciente__card">
          <div class="oro-paciente__perfil">
            <div class="oro-paciente__media">
              <img src="" alt="<%= paciente.nombre %>" class="oro-paciente__image">
            </div>
            <strong class="oro-paciente__name">
              <%= paciente.nombre %> <%= paciente.apellido %>
            </strong>
            <small class="oro-paciente__detail">
              <%= paciente.correo %>
            </small>
          </div>
          <div class="oro-paciente__message">

          </div>
          <div class="oro-paciente__options">
            <div class="btn-group">
              <%= link_to 'Ver', paciente,class: 'btn'  %>
              <%= link_to 'Editar', edit_paciente_path(paciente), class: 'btn' %>
              <%= link_to 'Eliminar', paciente, method: :delete, data: { confirm: '¿Estás seguro?' },class: 'btn'  %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <div class="oro-paciente__list oro-paciente__list--table">
      <div class="table-resposive">
        <table class="table">
          <thead>
          <tr>
            <th>Nombre</th>
            <th>Apellido</th>
            <th>Documento</th>
            <th>Celular</th>
            <th>Teléfono</th>
            <th>Email</th>
            <th colspan="3"></th>
          </tr>
          </thead>

          <tbody>
          <% @pacientes.each do |paciente| %>
            <tr>
              <td><%= paciente.nombre %></td>
              <td><%= paciente.apellido %></td>
              <td><%= paciente.documento %></td>
              <td><%= paciente.celular %></td>
              <td><%= paciente.telefono %></td>
              <td><%= paciente.correo %></td>
              <td><%= link_to 'Ver', paciente %></td>
              <td><%= link_to 'Editar', edit_paciente_path(paciente) %></td>
              <td><%= link_to 'Eliminar', paciente, method: :delete, data: { confirm: '¿Estás seguro?' } %></td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
<% end %>

  <script type="text/javascript" charset="utf-8">
      $('.oro-subnavbar__link').removeClass('oro-subnavbar__link--active')
      $('#nav-pacientes').addClass('oro-subnavbar__link--active')
  </script>
<br>
</div>

app/views/pacientes/new.html.erb
<div class="row oro-paciente__form">
  <%= render 'form', paciente: @paciente %>
</div>
<div class="oro-paciente__options">
  <%= link_to 'Regresar', pacientes_path %>
</div>

app/views/pacientes/show.html.erb
<div class="container">
  <div class="oro-paciente__card oro-paciente__card--fluid">
    <div class="row">
      <div class="col-md-4">
        <div class="oro-paciente__media">
          <img src="" alt="<%= @paciente.nombre %>" class="oro-paciente__image" id="oro-paciente__image">
        </div>
      </div>
      <div class="col-md-4">
        <p>
          <strong>Nombre:</strong>
          <%= @paciente.nombre %>
        </p>
        <p>
          <strong>Apellido:</strong>
          <%= @paciente.apellido %>
        </p>
      </div>
      <div class="col-md-4">
        <p>
          <strong>Documento:</strong>
          <%= @paciente.documento %>
        </p>
        <p>
          <strong>Usuario:</strong>
          <%= @paciente.usuario.nombres %>
        </p>
      </div>
    </div>
    <div class="row">
      <div class="col-md-4">
        <p>
          <strong>Tipo documento:</strong>
          <%= @paciente.tipo_documento %>
        </p>
      </div>
      <div class="col-md-4">
        <p>
          <strong>Genero:</strong>
          <%= @paciente.genero %>
        </p>
      </div>
      <div class="col-md-4">
        <p>
          <strong>Fecha nacimiento:</strong>
          <%= @paciente.f_nacimiento %>
        </p>
      </div>
    </div>
    <div class="row">
      <div class="col-md-4">
        <p>
          <strong>Edad:</strong>
          <%= @paciente.edad %>
        </p>
      </div>
      <div class="col-md-4">
        <p>
          <strong>País nacimiento:</strong>
          <%= @paciente.pais_nacimiento %>
        </p>
      </div>
      <!--<div class="col-md-4">
        <p>
          <strong>Nombre departamento:</strong>
          <%#<%= @paciente.n_departamento %>
        </p>
      </div>-->
    </div>
    <div class="row">
      <div class="col-md-4">
        <p>
          <strong>Ciudad:</strong>
          <%= @paciente.n_ciudad %>
        </p>
      </div>
      <div class="col-md-4">
        <p>
          <strong>Aseguradora:</strong>
          <%= @paciente.aseguradora %>
        </p>
      </div>
      <div class="col-md-4">
        <p>
          <strong>Raza:</strong>
          <%= @paciente.raza %>
        </p>
      </div>
    </div>
    <div class="row">
      <!--<div class="col-md-4">
        <p>
          <strong>Etnia:</strong>
          <%# <%= @paciente.etnia %>
        </p>
      </div>-->
      <!--<div class="col-md-4">
        <p>
          <strong>País residencia:</strong>
          <%#<%= @paciente.pais_residencia %>
        </p>
      </div>-->
      <!--<div class="col-md-4">
        <p>
          <strong>R departamento:</strong>
          <%#<%= @paciente.r_departamento %>
        </p>
      </div>-->
    </div>
    <div class="row">
      <div class="col-md-4">
        <p>
          <strong>Ciudad residencia:</strong>
          <%= @paciente.r_ciudad %>
        </p>
      </div>
      <div class="col-md-4">
        <p>
          <strong>Dirección residencia:</strong>
          <%= @paciente.r_direccion %>
        </p>
      </div>
      <div class="col-md-4">
        <p>
          <strong>Estado Civil:</strong>
          <%= @paciente.estado %>
        </p>
      </div>
    </div>
    <div class="row">
      <!--<div class="col-md-4">
        <p>
          <strong>Pais estancia:</strong>
          <%#<%= @paciente.pais_estancia %>
        </p>
      </div>
      <div class="col-md-4">
        <p>
          <strong>E departamento:</strong>
          <%#<%= @paciente.e_departamento %>
        </p>
      </div>
      <div class="col-md-4">
        <p>
          <strong>E ciudad:</strong>
          <%#<%= @paciente.e_ciudad %>
        </p>
      </div> -->
    </div>
    <div class="row">
      <div class="col-md-4">
        <!--<p>
          <strong>Religion:</strong>
          <%# <%= @paciente.religion %>
        </p>-->
      </div>
      <div class="col-md-4">
        <p>
          <strong>Celular:</strong>
          <%= @paciente.celular %>
        </p>
      </div>
      <div class="col-md-4">
        <p>
          <strong>Teléfono:</strong>
          <%= @paciente.telefono %>
        </p>
      </div>
    </div>
    <div class="row">
      <div class="col-md-4">
        <p>
          <strong>Email:</strong>
          <%= @paciente.correo %>
        </p>
      </div>
      <div class="col-md-2"></div>
      <div class="oro-show__actions col-md-6">
        <div class="col-md-2 pull-right">
          <%= link_to 'Regresar', pacientes_path, 'class': 'btn btn-default' %>
        </div>
        <div class="col-md-2 pull-right">
          <%= link_to 'Editar', edit_paciente_path(@paciente) %>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
  <div class="container">
  <div class="oro-paciente__card oro-paciente__card--fluid">
    <div class="oro-metrics__actions">
      <%= link_to 'Nueva Foto', new_foto_path , 'class': 'btn btn-primary' %>
    </div>
    <div class="table-responsive">
      <table class="table table-hover">
        <thead>
        <thead>
        <tr>
          <th>Foto</th>
          <th>Fecha subida</th>
          <th>Foto titulo</th>
          <th>Usuario</th>
          <th>Paciente</th>
          <th>Opciones</th>
        </tr>
        </thead>

        <tbody>
        <% @paciente.fotos.each do |foto| %>
          <tr>
            <td>
              <img class="oro-metrics__foto-min" src="<%= foto.img_lateral %>" alt="">
              <img class="oro-metrics__foto-min" src="<%= foto.img_frontal %>" alt="">
            </td>
            <td><%= foto.foto_titulo %></td>
            <td><%= foto.foto_titulo %></td>
            <td><%= foto.usuario.nombres %></td>
            <td><%= foto.paciente.nombre %></td>
            <td>
              <%= link_to 'Ver', foto %> |
              <%= link_to 'Editar', edit_foto_path(foto) %> |
              <%= link_to 'Eliminar', foto, method: :delete, data: { confirm: '¿Estás seguro?' } %>
            </td>

          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<script>
  function  getLastFotoPaciente() {
      $('#oro-paciente__image').attr('src',$($('.oro-metrics__foto-min')[$('.oro-metrics__foto-min').length - 1]).attr('src'));
  }
  getLastFotoPaciente();
</script>