config/routes.rb
Rails.application.routes.draw do

  root 'paginas#inicio'

  devise_for :usuarios,
             path: '',
             path_names: {sign_in: 'ingresar', sign_out: 'salir', edit: 'perfil', sign_up: 'registrar'},
             controllers: {registrations: 'registrations'}

  resources :consentimientos
  resources :pacientes
  resources :fotos
  resources :fotodiagnosticos
  resources :campodiagnosticos
  resources :seguimientos

end

app/models/seguimiento.rb
class Seguimiento < ApplicationRecord

  has_attached_file :img_frontal, styles: { medium: "600x600>", thumb: "200x200>" }
  validates_attachment_content_type :img_frontal, content_type: /\Aimage\/.*\z/

  has_attached_file :img_lateral, styles: { medium: "600x600>", thumb: "200x200>" }
  validates_attachment_content_type :img_lateral, content_type: /\Aimage\/.*\z/

  belongs_to :usuario
  belongs_to :paciente
end

app/controllers/seguimientos_controller.rb
class SeguimientosController < ApplicationController
  before_action :set_seguimiento, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_usuario!, except: [:index, :show]

  # GET /seguimientos
  # GET /seguimientos.json
  def index
    @seguimientos = Seguimiento.all
  end

  # GET /seguimientos/1
  # GET /seguimientos/1.json
  def show
  end

  # GET /seguimientos/new
  def new
    @seguimiento = Seguimiento.new
  end

  # GET /seguimientos/1/edit
  def edit
  end

  # POST /seguimientos
  # POST /seguimientos.json
  def create
    @seguimiento = current_usuario.seguimientos.new(seguimiento_params)

    respond_to do |format|
      if @seguimiento.save
        format.html { redirect_to @seguimiento, notice: 'Seguimiento fue creado con éxito.' }
        format.json { render :show, status: :created, location: @seguimiento }
      else
        format.html { render :new }
        format.json { render json: @seguimiento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /seguimientos/1
  # PATCH/PUT /seguimientos/1.json
  def update
    respond_to do |format|
      if @seguimiento.update(seguimiento_params)
        format.html { redirect_to @seguimiento, notice: 'Seguimiento fue actualizado con éxito.' }
        format.json { render :show, status: :ok, location: @seguimiento }
      else
        format.html { render :edit }
        format.json { render json: @seguimiento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /seguimientos/1
  # DELETE /seguimientos/1.json
  def destroy
    @seguimiento.destroy
    respond_to do |format|
      format.html { redirect_to seguimientos_url, notice: 'Seguimiento fue destruido con éxito.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_seguimiento
      @seguimiento = Seguimiento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def seguimiento_params
      params.require(:seguimiento).permit(:n_tecnica, :n_procedimiento, :n_frecuencia_aplicacion, :img_frontal, :img_lateral, :evolucion_foto, :resultado, :usuario_id, :paciente_id)
    end
end

app/helpers/seguimientos_helper.rb
module SeguimientosHelper
end

app/views/seguimientos/_form.html.erb
<%= form_for(seguimiento) do |f| %>
  <% if seguimiento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(seguimiento.errors.count, "error") %> prohibited this seguimiento from being saved:</h2>

      <ul>
      <% seguimiento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :n_tecnica %>
    <%= f.text_field :n_tecnica %>
  </div>

  <div class="field">
    <%= f.label :n_procedimiento %>
    <%= f.text_field :n_procedimiento %>
  </div>

  <div class="field">
    <%= f.label :n_frecuencia_aplicacion %>
    <%= f.text_field :n_frecuencia_aplicacion %>
  </div>

  <div class="field">
    <%= f.label :img_frontal %>
    <%= f.file_field :img_frontal %>
  </div>

  <div class="field">
    <%= f.label :img_lateral %>
    <%= f.file_field :img_lateral %>
  </div>

  <div class="field">
    <%= f.label :evolucion_foto %>
    <%= f.text_field :evolucion_foto %>
  </div>

  <div class="field">
    <%= f.label :resultado %>
    <%= f.text_field :resultado %>
  </div>

  <div class="field">
    <%= f.label :paciente_id %>
    <%= f.collection_select :paciente_id, Paciente.all, :id, :nombre %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/seguimientos/edit.html.erb
<h1>Editar Seguimiento</h1>

<%= render 'form', seguimiento: @seguimiento %>

<%= link_to 'Ver', @seguimiento %> |
<%= link_to 'Regresar', seguimientos_path %>

app/views/seguimientos/index.html.erb
<h1>Seguimientos</h1>

<table>
  <thead>
    <tr>
      <th>N tecnica</th>
      <th>N procedimiento</th>
      <th>N frecuencia aplicacion</th>
      <th>Evolucion foto</th>
      <th>Resultado</th>
      <th>Usuario</th>
      <th>Paciente</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @seguimientos.each do |seguimiento| %>
      <tr>
        <td><%= seguimiento.n_tecnica %></td>
        <td><%= seguimiento.n_procedimiento %></td>
        <td><%= seguimiento.n_frecuencia_aplicacion %></td>
        <td><%= seguimiento.evolucion_foto %></td>
        <td><%= seguimiento.resultado %></td>
        <td><%= seguimiento.usuario %></td>
        <td><%= seguimiento.paciente %></td>
        <td><%= link_to 'Ver', seguimiento %></td>
        <td><%= link_to 'Editar', edit_seguimiento_path(seguimiento) %></td>
        <td><%= link_to 'Eliminar', seguimiento, method: :delete, data: { confirm: '¿Estás seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Seguimiento', new_seguimiento_path %>

app/views/seguimientos/new.html.erb
<h1>Nuevo Seguimiento</h1>

<%= render 'form', seguimiento: @seguimiento %>

<%= link_to 'Regresar', seguimientos_path %>

app/views/seguimientos/show.html.erb
<p>
  <strong>N tecnica:</strong>
  <%= @seguimiento.n_tecnica %>
</p>

<p>
  <strong>N procedimiento:</strong>
  <%= @seguimiento.n_procedimiento %>
</p>

<p>
  <strong>N frecuencia aplicacion:</strong>
  <%= @seguimiento.n_frecuencia_aplicacion %>
</p>

<p>
  <strong>Evolucion foto:</strong>
  <%= @seguimiento.evolucion_foto %>
</p>

<p>
  <strong>Resultado:</strong>
  <%= @seguimiento.resultado %>
</p>

<p>
  <strong>Usuario:</strong>
  <%= @seguimiento.usuario %>
</p>

<p>
  <strong>Paciente:</strong>
  <%= @seguimiento.paciente %>
</p>

<%= link_to 'Editar', edit_seguimiento_path(@seguimiento) %> |
<%= link_to 'Regresar', seguimientos_path %>