config/routes.rb
Rails.application.routes.draw do

  root 'paginas#inicio'

  devise_for :usuarios,
             path: '',
             path_names: {sign_in: 'ingresar', sign_out: 'salir', edit: 'perfil', sign_up: 'registrar'},
             controllers: {registrations: 'registrations'}

  resources :consentimientos
  resources :pacientes
  resources :fotos
  resources :fotodiagnosticos
  resources :campodiagnosticos
  resources :seguimientos

end

app/models/foto.rb
class Foto < ApplicationRecord

  has_attached_file :img_frontal, styles: { medium: "600x600>", thumb: "200x200>" }
  validates_attachment_content_type :img_frontal, content_type: /\Aimage\/.*\z/

  has_attached_file :img_lateral, styles: { medium: "600x600>", thumb: "200x200>" }
  validates_attachment_content_type :img_lateral, content_type: /\Aimage\/.*\z/

  belongs_to :usuario
  belongs_to :paciente
  has_many :fotodiagnosticos
  
end

app/controllers/fotos_controller.rb
class FotosController < ApplicationController
  before_action :set_foto, only: [:show,:showkonva, :edit, :update, :destroy]
  before_action :authenticate_usuario!, except: [:index, :show, :showkonva]

  # GET /fotos
  # GET /fotos.json
  def index
    @fotos = Foto.all
  end

  # GET /fotos/1
  # GET /fotos/1.json
  def show
  end


  # GET /fotos/1
  # GET /fotos/1.json
  def showkonva
  end

  # GET /fotos/new
  def new
    @foto = Foto.new
  end

  # GET /fotos/1/edit
  def edit
  end

  # POST /fotos
  # POST /fotos.json
  def create
    @foto = current_usuario.fotos.new(foto_params)

    respond_to do |format|
      if @foto.save
        format.html { redirect_to @foto, notice: 'Foto fue creado con éxito.' }
        format.json { render :show, status: :created, location: @foto }
      else
        format.html { render :new }
        format.json { render json: @foto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fotos/1
  # PATCH/PUT /fotos/1.json
  def update
    respond_to do |format|
      if @foto.update(foto_params)
        format.html { redirect_to @foto, notice: 'Foto fue actualizado con éxito.' }
        format.json { render :show, status: :ok, location: @foto }
      else
        format.html { render :edit }
        format.json { render json: @foto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fotos/1
  # DELETE /fotos/1.json
  def destroy
    @foto.destroy
    respond_to do |format|
      format.html { redirect_to fotos_url, notice: 'Foto fue destruido con éxito.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_foto
      @foto = Foto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def foto_params
      params.require(:foto).permit(:f_subida, :foto_titulo, :img_frontal, :img_lateral, :usuario_id, :paciente_id)
    end
end

app/helpers/fotos_helper.rb
module FotosHelper
end

app/views/fotos/_form.html.erb
<%= form_for(foto) do |f| %>
  <% if foto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(foto.errors.count, "error") %> prohibited this foto from being saved:</h2>

      <ul>
      <% foto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <div class="oro-metrics__media-upload">
          <div class="field">
            <%= f.label :img_frontal %>
            <%= f.file_field :img_frontal %>
          </div>
        </div>
      </div>
      <div class="col-md-6">
        <div class="oro-metrics__media-upload">
          <div class="field">
            <%= f.label :img_lateral %>
            <%= f.file_field :img_lateral %>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <br>
        <hr>
        <br>
      </div>
    </div>
    <div class="row">
      <div class="col-md-4">
        <div class="form-group">
          <%= f.label :fecha_subida, class: 'form-label' %>
          <%= f.date_select :f_subida, class: 'form-control' %>
        </div>
      </div>
      <div class="col-md-4">
        <div class="field">
          <%= f.label :foto_titulo, class: 'form-label' %>
          <%= f.text_field :foto_titulo, class: 'form-control'  %>
        </div>
      </div>
      <div class="col-md-4">
        <div class="field">
          <%= f.label :paciente_id, class: 'form-label' %>
          <%= f.collection_select :paciente_id, Paciente.all, :id, :nombre , class: 'form-control' %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-4 col-md-offset-8">
        <div class="actions">
          <%= link_to 'Regresar', fotos_path %>
          <%= f.submit %>
        </div>
      </div>
    </div>
  </div>

<% end %>

app/views/fotos/edit.html.erb
<h1>Editar Foto</h1>

<%= render 'form', foto: @foto %>

<%= link_to 'Ver', @foto %> |
<%= link_to 'Regresar', fotos_path %>

app/views/fotos/index.html.erb
<div class="oro-metrics">
  <div class="oro-metrics__actions">
    <%= link_to 'Nueva Foto', new_foto_path , 'class': 'btn btn-primary' %>
  </div>
  <div class="table-responsive">
  <table class="table table-hover">
    <thead>
    <tr>
      <th>Foto</th>
      <th>Fecha subida</th>
      <th>Foto titulo</th>
      <th>Usuario</th>
      <th>Paciente</th>
      <th>Opciones</th>
    </tr>
    </thead>

    <tbody>
    <% @fotos.each do |foto| %>
      <tr>
        <td>
          <img class="oro-metrics__foto-min" src="<%= foto.img_lateral %>" alt="">
          <img class="oro-metrics__foto-min" src="<%= foto.img_frontal %>" alt="">
        </td>
        <td><%= foto.foto_titulo %></td>
        <td><%= foto.foto_titulo %></td>
        <td><%= foto.usuario.nombres %></td>
        <td><%= foto.paciente.nombre %></td>
        <td>
          <%= link_to 'Ver', foto %> |
          <%= link_to 'Editar', edit_foto_path(foto) %> |
          <%= link_to 'Eliminar', foto, method: :delete, data: { confirm: '¿Estás seguro?' } %>
        </td>

      </tr>
    <% end %>
    </tbody>
  </table>
  </div>
  <br>
  <script type="text/javascript" charset="utf-8">
      $('.oro-subnavbar__link').removeClass('oro-subnavbar__link--active')
      $('#nav-matrics').addClass('oro-subnavbar__link--active')
  </script>
</div>

app/views/fotos/new.html.erb
<div class="row">
  <div class="col-md-12">
    <h3 class="text-center">Nueva Foto</h3>
  </div>
</div>
<div class="row">
  <%= render 'form', foto: @foto %>
</div>