config/routes.rb
Rails.application.routes.draw do

  root 'paginas#inicio'

  devise_for :usuarios,
             path: '',
             path_names: {sign_in: 'ingresar', sign_out: 'salir', edit: 'perfil', sign_up: 'registrar'},
             controllers: {registrations: 'registrations'}

  resources :consentimientos
  resources :pacientes
  resources :fotos
  resources :fotodiagnosticos
  resources :campodiagnosticos
  resources :seguimientos

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/campodiagnostico.rb
class Campodiagnostico < ApplicationRecord
  belongs_to :usuario
  belongs_to :fotodiagnostico
end

app/models/consentimiento.rb
class Consentimiento < ApplicationRecord
  belongs_to :usuario
end

app/models/foto.rb
class Foto < ApplicationRecord

  has_attached_file :img_frontal, styles: { medium: "600x600>", thumb: "200x200>" }
  validates_attachment_content_type :img_frontal, content_type: /\Aimage\/.*\z/

  has_attached_file :img_lateral, styles: { medium: "600x600>", thumb: "200x200>" }
  validates_attachment_content_type :img_lateral, content_type: /\Aimage\/.*\z/

  belongs_to :usuario
  belongs_to :paciente
  has_many :fotodiagnosticos
  
end

app/models/fotodiagnostico.rb
class Fotodiagnostico < ApplicationRecord
  belongs_to :usuario
  belongs_to :foto
  belongs_to :paciente
  has_many :campodiagnosticos
end

app/models/paciente.rb
class Paciente < ApplicationRecord
  belongs_to :usuario
  has_many :fotos
  has_many :fotodiagnosticos
  has_many :seguimientos
end

app/models/seguimiento.rb
class Seguimiento < ApplicationRecord

  has_attached_file :img_frontal, styles: { medium: "600x600>", thumb: "200x200>" }
  validates_attachment_content_type :img_frontal, content_type: /\Aimage\/.*\z/

  has_attached_file :img_lateral, styles: { medium: "600x600>", thumb: "200x200>" }
  validates_attachment_content_type :img_lateral, content_type: /\Aimage\/.*\z/

  belongs_to :usuario
  belongs_to :paciente
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable

  validates :nombres, presence: true, length: {maximum: 50}

  has_many :consentimientos
  has_many :pacientes
  has_many :fotos
  has_many :fotodiagnosticos
  has_many :campodiagnosticos
  has_many :seguimientos

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nombres])
    devise_parameter_sanitizer.permit(:account_update, keys: [:nombres, :empresa, :telefono])
  end
end

app/controllers/fotos_controller.rb
class FotosController < ApplicationController
  before_action :set_foto, only: [:show,:showkonva, :edit, :update, :destroy]
  before_action :authenticate_usuario!, except: [:index, :show, :showkonva]

  # GET /fotos
  # GET /fotos.json
  def index
    @fotos = Foto.all
  end

  # GET /fotos/1
  # GET /fotos/1.json
  def show
  end


  # GET /fotos/1
  # GET /fotos/1.json
  def showkonva
  end

  # GET /fotos/new
  def new
    @foto = Foto.new
  end

  # GET /fotos/1/edit
  def edit
  end

  # POST /fotos
  # POST /fotos.json
  def create
    @foto = current_usuario.fotos.new(foto_params)

    respond_to do |format|
      if @foto.save
        format.html { redirect_to @foto, notice: 'Foto fue creado con éxito.' }
        format.json { render :show, status: :created, location: @foto }
      else
        format.html { render :new }
        format.json { render json: @foto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fotos/1
  # PATCH/PUT /fotos/1.json
  def update
    respond_to do |format|
      if @foto.update(foto_params)
        format.html { redirect_to @foto, notice: 'Foto fue actualizado con éxito.' }
        format.json { render :show, status: :ok, location: @foto }
      else
        format.html { render :edit }
        format.json { render json: @foto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fotos/1
  # DELETE /fotos/1.json
  def destroy
    @foto.destroy
    respond_to do |format|
      format.html { redirect_to fotos_url, notice: 'Foto fue destruido con éxito.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_foto
      @foto = Foto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def foto_params
      params.require(:foto).permit(:f_subida, :foto_titulo, :img_frontal, :img_lateral, :usuario_id, :paciente_id)
    end
end

app/controllers/pacientes_controller.rb
class PacientesController < ApplicationController
  before_action :set_paciente, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_usuario!, except: [:index, :show]

  # GET /pacientes
  # GET /pacientes.json
  def index
    @pacientes = Paciente.all.order("created_at desc")
  end

  # GET /pacientes/1
  # GET /pacientes/1.json
  def show
  end

  # GET /pacientes/new
  def new
    @paciente = Paciente.new
  end

  # GET /pacientes/1/edit
  def edit
  end

  # POST /pacientes
  # POST /pacientes.json
  def create
    @paciente = current_usuario.pacientes.new(paciente_params)

    respond_to do |format|
      if @paciente.save
        format.html { redirect_to @paciente, notice: 'Paciente fue creado con éxito.' }
        format.json { render :show, status: :created, location: @paciente }
      else
        format.html { render :new }
        format.json { render json: @paciente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pacientes/1
  # PATCH/PUT /pacientes/1.json
  def update
    respond_to do |format|
      if @paciente.update(paciente_params)
        format.html { redirect_to @paciente, notice: 'Paciente fue actualizado con éxito.' }
        format.json { render :show, status: :ok, location: @paciente }
      else
        format.html { render :edit }
        format.json { render json: @paciente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pacientes/1
  # DELETE /pacientes/1.json
  def destroy
    @paciente.destroy
    respond_to do |format|
      format.html { redirect_to pacientes_url, notice: 'Paciente fue destruido con éxito.' }
      format.json { head :no_content }
    end
  end

  private

    def set_paciente
      @paciente = Paciente.find(params[:id])
    end

    def paciente_params
      params.require(:paciente).permit(:nombre, :apellido, :genero, :tipo_documento, :documento, :f_nacimiento, :edad, :pais_nacimiento, :n_departamento, :n_ciudad, :aseguradora, :raza, :etnia, :pais_residencia, :r_departamento, :r_ciudad, :r_direccion, :estado, :pais_estancia, :e_departamento, :e_ciudad, :religion, :celular, :telefono, :correo, :usuario_id)
    end
end

app/controllers/paginas_controller.rb
class PaginasController < ApplicationController
  def inicio

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campodiagnosticos_helper.rb
module CampodiagnosticosHelper
end

app/helpers/consentimientos_helper.rb
module ConsentimientosHelper
end

app/helpers/fotodiagnosticos_helper.rb
module FotodiagnosticosHelper
end

app/helpers/fotos_helper.rb
module FotosHelper
end

app/helpers/pacientes_helper.rb
module PacientesHelper
end

app/helpers/paginas_helper.rb
module PaginasHelper
end

app/helpers/seguimientos_helper.rb
module SeguimientosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OrofacialMetrics</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0,user-scalable=no">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'shared/navbar' %>
    <%= render 'shared/message' %>

    <div class="oro-main"   <% if (!usuario_signed_in?) %> style="margin-top: 50px" <% end %> >
      <%= yield %>
    </div>

  </body>
</html>

app/views/shared/_devisemes.html.erb
<% unless resource.errors.empty? %>
  <script type="text/javascript">
    <% resource.errors.full_messages.each do |value| %>
      toastr.error('<%= value %>')
    <% end %>
  </script>
<% end %>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
    <% flash.each do |key, value| %>
      <% type = key.to_s.gsub('alert', 'error').gsub('notice', 'success') %>
      toastr['<%= type %>']('<%= value %>')
    <% end %>
  </script>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default oro-navbar">
  <div class="container-fluid">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"><img src="<%= asset_path 'logo.png' %>"></a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="dropdown oro-navbar__link">
          <!--<a href="#" class="dropdown-toggle" data-toggle="dropdown"
             role="button" aria-haspopup="true" aria-expanded="false">
             Pacientes <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="/pacientes/new">Registro de Paciente</a></li>
            <li><a href="/consentimientos/new">Consentimiento Informado</a></li>
          </ul>-->
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if (!usuario_signed_in?) %>
          <li class="oro-navbar__link"><%= link_to "Iniciar sesión", new_usuario_session_path %></li>
          <li class="oro-navbar__link"><%= link_to "Crear cuenta", new_usuario_registration_path %></li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle oro-navbar__link"  data-toggle="dropdown"
                   role="button" aria-haspopup="true" aria-expanded="false" >
                   <%= current_usuario.nombres %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Editar perfil", edit_usuario_registration_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Cerrar sesión", destroy_usuario_session_path, method: :delete %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
  <% if (usuario_signed_in?) %>
  <div class="container-fluid oro-subnavbar">
    <ul class="nav navbar-nav oro-subnavbar__nav">
      <li class="oro-subnavbar__link oro-subnavbar__link--active" id="nav-pacientes"><a href="/pacientes">Pacientes</a></li>
      <li class="oro-subnavbar__link" id="nav-matrics"><a href="/fotos">Metrics</a></li>
      <li class="oro-subnavbar__link" id="nav-show"><a href="/">Inicio</a></li>
    </ul>
  </div>
  <% end %>
</nav>

app/views/shared/sidebar/_pacientes.html.erb
<div class="oro-sidebar">
  <ul class="nav">
    <li class="oro-sidebar--link">
      <a href="/pacientes">Pacientes</a>
    </li>
    <li class="oro-sidebar--link">
      <a href="/consentimientos">Consentimientos</a>
    </li>
    <li class="oro-sidebar--link"></li>
  </ul>
</div>